[package]
name = "disclose_bytes_evm"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.32.0"

[dependencies]
disclose = { path = "../../../../lib/disclose" }
commitment = { path = "../../../../lib/commitment/scoped-nullifier" }