[workspace]
members = [
    "src/noir/bin/compare/citizenship",
    "src/noir/bin/compare/age",
    "src/noir/bin/disclose/flags",
    "src/noir/bin/disclose/bytes",
    "src/noir/bin/main/outer",
    "src/noir/bin/data-check/expiry",
    "src/noir/bin/data-check/integrity",
    "src/noir/bin/exclusion-check/country",
    "src/noir/bin/inclusion-check/country",
    "src/noir/bin/sig-check/dsc/tbs_700/ecdsa/nist/p256",
    "src/noir/bin/sig-check/dsc/tbs_1000/ecdsa/nist/p256",
    "src/noir/bin/sig-check/dsc/tbs_1200/ecdsa/nist/p256",
    "src/noir/bin/sig-check/dsc/tbs_1500/ecdsa/nist/p256",
    "src/noir/bin/sig-check/dsc/tbs_700/ecdsa/nist/p384",
    "src/noir/bin/sig-check/dsc/tbs_1000/ecdsa/nist/p384",
    "src/noir/bin/sig-check/dsc/tbs_1200/ecdsa/nist/p384",
    "src/noir/bin/sig-check/dsc/tbs_1500/ecdsa/nist/p384",
    "src/noir/bin/sig-check/dsc/tbs_700/ecdsa/nist/p521",
    "src/noir/bin/sig-check/dsc/tbs_1000/ecdsa/nist/p521",
    "src/noir/bin/sig-check/dsc/tbs_1200/ecdsa/nist/p521",
    "src/noir/bin/sig-check/dsc/tbs_1500/ecdsa/nist/p521",
    "src/noir/bin/sig-check/dsc/tbs_700/ecdsa/brainpool/256r1",
    "src/noir/bin/sig-check/dsc/tbs_1000/ecdsa/brainpool/256r1",
    "src/noir/bin/sig-check/dsc/tbs_1200/ecdsa/brainpool/256r1",
    "src/noir/bin/sig-check/dsc/tbs_1500/ecdsa/brainpool/256r1",
    "src/noir/bin/sig-check/dsc/tbs_700/ecdsa/brainpool/384r1",
    "src/noir/bin/sig-check/dsc/tbs_1000/ecdsa/brainpool/384r1",
    "src/noir/bin/sig-check/dsc/tbs_1200/ecdsa/brainpool/384r1",
    "src/noir/bin/sig-check/dsc/tbs_1500/ecdsa/brainpool/384r1",
    "src/noir/bin/sig-check/dsc/tbs_700/ecdsa/brainpool/512r1",
    "src/noir/bin/sig-check/dsc/tbs_1000/ecdsa/brainpool/512r1",
    "src/noir/bin/sig-check/dsc/tbs_1200/ecdsa/brainpool/512r1",
    "src/noir/bin/sig-check/dsc/tbs_1500/ecdsa/brainpool/512r1",
    "src/noir/bin/sig-check/dsc/tbs_700/ecdsa/brainpool/256t1",
    "src/noir/bin/sig-check/dsc/tbs_1000/ecdsa/brainpool/256t1",
    "src/noir/bin/sig-check/dsc/tbs_1200/ecdsa/brainpool/256t1",
    "src/noir/bin/sig-check/dsc/tbs_1500/ecdsa/brainpool/256t1",
    "src/noir/bin/sig-check/dsc/tbs_700/ecdsa/brainpool/384t1",
    "src/noir/bin/sig-check/dsc/tbs_1000/ecdsa/brainpool/384t1",
    "src/noir/bin/sig-check/dsc/tbs_1200/ecdsa/brainpool/384t1",
    "src/noir/bin/sig-check/dsc/tbs_1500/ecdsa/brainpool/384t1",
    "src/noir/bin/sig-check/dsc/tbs_700/ecdsa/brainpool/512t1",
    "src/noir/bin/sig-check/dsc/tbs_1000/ecdsa/brainpool/512t1",
    "src/noir/bin/sig-check/dsc/tbs_1200/ecdsa/brainpool/512t1",
    "src/noir/bin/sig-check/dsc/tbs_1500/ecdsa/brainpool/512t1",
    "src/noir/bin/sig-check/dsc/tbs_700/rsa/pss/1024",
    "src/noir/bin/sig-check/dsc/tbs_1000/rsa/pss/1024",
    "src/noir/bin/sig-check/dsc/tbs_1200/rsa/pss/1024",
    "src/noir/bin/sig-check/dsc/tbs_1500/rsa/pss/1024",
    "src/noir/bin/sig-check/dsc/tbs_700/rsa/pss/2048",
    "src/noir/bin/sig-check/dsc/tbs_1000/rsa/pss/2048",
    "src/noir/bin/sig-check/dsc/tbs_1200/rsa/pss/2048",
    "src/noir/bin/sig-check/dsc/tbs_1500/rsa/pss/2048",
    "src/noir/bin/sig-check/dsc/tbs_700/rsa/pss/3072",
    "src/noir/bin/sig-check/dsc/tbs_1000/rsa/pss/3072",
    "src/noir/bin/sig-check/dsc/tbs_1200/rsa/pss/3072",
    "src/noir/bin/sig-check/dsc/tbs_1500/rsa/pss/3072",
    "src/noir/bin/sig-check/dsc/tbs_700/rsa/pss/4096",
    "src/noir/bin/sig-check/dsc/tbs_1000/rsa/pss/4096",
    "src/noir/bin/sig-check/dsc/tbs_1200/rsa/pss/4096",
    "src/noir/bin/sig-check/dsc/tbs_1500/rsa/pss/4096",
    "src/noir/bin/sig-check/dsc/tbs_700/rsa/pkcs/1024",
    "src/noir/bin/sig-check/dsc/tbs_1000/rsa/pkcs/1024",
    "src/noir/bin/sig-check/dsc/tbs_1200/rsa/pkcs/1024",
    "src/noir/bin/sig-check/dsc/tbs_1500/rsa/pkcs/1024",
    "src/noir/bin/sig-check/dsc/tbs_700/rsa/pkcs/2048",
    "src/noir/bin/sig-check/dsc/tbs_1000/rsa/pkcs/2048",
    "src/noir/bin/sig-check/dsc/tbs_1200/rsa/pkcs/2048",
    "src/noir/bin/sig-check/dsc/tbs_1500/rsa/pkcs/2048",
    "src/noir/bin/sig-check/dsc/tbs_700/rsa/pkcs/3072",
    "src/noir/bin/sig-check/dsc/tbs_1000/rsa/pkcs/3072",
    "src/noir/bin/sig-check/dsc/tbs_1200/rsa/pkcs/3072",
    "src/noir/bin/sig-check/dsc/tbs_1500/rsa/pkcs/3072",
    "src/noir/bin/sig-check/dsc/tbs_700/rsa/pkcs/4096",
    "src/noir/bin/sig-check/dsc/tbs_1000/rsa/pkcs/4096",
    "src/noir/bin/sig-check/dsc/tbs_1200/rsa/pkcs/4096",
    "src/noir/bin/sig-check/dsc/tbs_1500/rsa/pkcs/4096",
    "src/noir/bin/sig-check/id-data/tbs_700/ecdsa/nist/p256",
    "src/noir/bin/sig-check/id-data/tbs_1000/ecdsa/nist/p256",
    "src/noir/bin/sig-check/id-data/tbs_1200/ecdsa/nist/p256",
    "src/noir/bin/sig-check/id-data/tbs_1500/ecdsa/nist/p256",
    "src/noir/bin/sig-check/id-data/tbs_700/ecdsa/nist/p384",
    "src/noir/bin/sig-check/id-data/tbs_1000/ecdsa/nist/p384",
    "src/noir/bin/sig-check/id-data/tbs_1200/ecdsa/nist/p384",
    "src/noir/bin/sig-check/id-data/tbs_1500/ecdsa/nist/p384",
    "src/noir/bin/sig-check/id-data/tbs_700/ecdsa/nist/p521",
    "src/noir/bin/sig-check/id-data/tbs_1000/ecdsa/nist/p521",
    "src/noir/bin/sig-check/id-data/tbs_1200/ecdsa/nist/p521",
    "src/noir/bin/sig-check/id-data/tbs_1500/ecdsa/nist/p521",
    "src/noir/bin/sig-check/id-data/tbs_700/ecdsa/brainpool/256r1",
    "src/noir/bin/sig-check/id-data/tbs_1000/ecdsa/brainpool/256r1",
    "src/noir/bin/sig-check/id-data/tbs_1200/ecdsa/brainpool/256r1",
    "src/noir/bin/sig-check/id-data/tbs_1500/ecdsa/brainpool/256r1",
    "src/noir/bin/sig-check/id-data/tbs_700/ecdsa/brainpool/384r1",
    "src/noir/bin/sig-check/id-data/tbs_1000/ecdsa/brainpool/384r1",
    "src/noir/bin/sig-check/id-data/tbs_1200/ecdsa/brainpool/384r1",
    "src/noir/bin/sig-check/id-data/tbs_1500/ecdsa/brainpool/384r1",
    "src/noir/bin/sig-check/id-data/tbs_700/ecdsa/brainpool/512r1",
    "src/noir/bin/sig-check/id-data/tbs_1000/ecdsa/brainpool/512r1",
    "src/noir/bin/sig-check/id-data/tbs_1200/ecdsa/brainpool/512r1",
    "src/noir/bin/sig-check/id-data/tbs_1500/ecdsa/brainpool/512r1",
    "src/noir/bin/sig-check/id-data/tbs_700/ecdsa/brainpool/256t1",
    "src/noir/bin/sig-check/id-data/tbs_1000/ecdsa/brainpool/256t1",
    "src/noir/bin/sig-check/id-data/tbs_1200/ecdsa/brainpool/256t1",
    "src/noir/bin/sig-check/id-data/tbs_1500/ecdsa/brainpool/256t1",
    "src/noir/bin/sig-check/id-data/tbs_700/ecdsa/brainpool/384t1",
    "src/noir/bin/sig-check/id-data/tbs_1000/ecdsa/brainpool/384t1",
    "src/noir/bin/sig-check/id-data/tbs_1200/ecdsa/brainpool/384t1",
    "src/noir/bin/sig-check/id-data/tbs_1500/ecdsa/brainpool/384t1",
    "src/noir/bin/sig-check/id-data/tbs_700/ecdsa/brainpool/512t1",
    "src/noir/bin/sig-check/id-data/tbs_1000/ecdsa/brainpool/512t1",
    "src/noir/bin/sig-check/id-data/tbs_1200/ecdsa/brainpool/512t1",
    "src/noir/bin/sig-check/id-data/tbs_1500/ecdsa/brainpool/512t1",
    "src/noir/bin/sig-check/id-data/tbs_700/rsa/pss/1024",
    "src/noir/bin/sig-check/id-data/tbs_1000/rsa/pss/1024",
    "src/noir/bin/sig-check/id-data/tbs_1200/rsa/pss/1024",
    "src/noir/bin/sig-check/id-data/tbs_1500/rsa/pss/1024",
    "src/noir/bin/sig-check/id-data/tbs_700/rsa/pss/2048",
    "src/noir/bin/sig-check/id-data/tbs_1000/rsa/pss/2048",
    "src/noir/bin/sig-check/id-data/tbs_1200/rsa/pss/2048",
    "src/noir/bin/sig-check/id-data/tbs_1500/rsa/pss/2048",
    "src/noir/bin/sig-check/id-data/tbs_700/rsa/pss/3072",
    "src/noir/bin/sig-check/id-data/tbs_1000/rsa/pss/3072",
    "src/noir/bin/sig-check/id-data/tbs_1200/rsa/pss/3072",
    "src/noir/bin/sig-check/id-data/tbs_1500/rsa/pss/3072",
    "src/noir/bin/sig-check/id-data/tbs_700/rsa/pss/4096",
    "src/noir/bin/sig-check/id-data/tbs_1000/rsa/pss/4096",
    "src/noir/bin/sig-check/id-data/tbs_1200/rsa/pss/4096",
    "src/noir/bin/sig-check/id-data/tbs_1500/rsa/pss/4096",
    "src/noir/bin/sig-check/id-data/tbs_700/rsa/pkcs/1024",
    "src/noir/bin/sig-check/id-data/tbs_1000/rsa/pkcs/1024",
    "src/noir/bin/sig-check/id-data/tbs_1200/rsa/pkcs/1024",
    "src/noir/bin/sig-check/id-data/tbs_1500/rsa/pkcs/1024",
    "src/noir/bin/sig-check/id-data/tbs_700/rsa/pkcs/2048",
    "src/noir/bin/sig-check/id-data/tbs_1000/rsa/pkcs/2048",
    "src/noir/bin/sig-check/id-data/tbs_1200/rsa/pkcs/2048",
    "src/noir/bin/sig-check/id-data/tbs_1500/rsa/pkcs/2048",
    "src/noir/bin/sig-check/id-data/tbs_700/rsa/pkcs/3072",
    "src/noir/bin/sig-check/id-data/tbs_1000/rsa/pkcs/3072",
    "src/noir/bin/sig-check/id-data/tbs_1200/rsa/pkcs/3072",
    "src/noir/bin/sig-check/id-data/tbs_1500/rsa/pkcs/3072",
    "src/noir/bin/sig-check/id-data/tbs_700/rsa/pkcs/4096",
    "src/noir/bin/sig-check/id-data/tbs_1000/rsa/pkcs/4096",
    "src/noir/bin/sig-check/id-data/tbs_1200/rsa/pkcs/4096",
    "src/noir/bin/sig-check/id-data/tbs_1500/rsa/pkcs/4096"
]
