[workspace]
members = [
    "crates/bin/data-check/expiry", 
    "crates/bin/data-check/integrity", 
    "crates/bin/sig-check/dsc/rsa/pkcs/1024",
    "crates/bin/sig-check/dsc/rsa/pkcs/2048",
    "crates/bin/sig-check/dsc/rsa/pkcs/3072",
    "crates/bin/sig-check/dsc/rsa/pkcs/4096",
    "crates/bin/sig-check/dsc/rsa/pss/1024",
    "crates/bin/sig-check/dsc/rsa/pss/2048",
    "crates/bin/sig-check/dsc/rsa/pss/3072",
    "crates/bin/sig-check/dsc/rsa/pss/4096",
    "crates/bin/sig-check/dsc/ecdsa/nist/p256",
    "crates/bin/sig-check/id-data/ecdsa/nist/p256",
    "crates/bin/sig-check/id-data/rsa/pkcs/1024",
    "crates/bin/sig-check/id-data/rsa/pkcs/2048",
    "crates/bin/sig-check/id-data/rsa/pkcs/3072",
    "crates/bin/sig-check/id-data/rsa/pkcs/4096",
    "crates/bin/sig-check/id-data/rsa/pss/1024",
    "crates/bin/sig-check/id-data/rsa/pss/2048",
    "crates/bin/sig-check/id-data/rsa/pss/3072",
    "crates/bin/sig-check/id-data/rsa/pss/4096",
    "crates/bin/compare/citizenship",
    "crates/bin/compare/age",
    "crates/bin/disclose/flags",
    "crates/bin/disclose/bytes",
    "crates/bin/main/outer"
]
