[workspace]
members = [
    "src/noir/bin/data-check/expiry",
    "src/noir/bin/data-check/integrity",
    "src/noir/bin/sig-check/dsc/rsa/pkcs/1024",
    "src/noir/bin/sig-check/dsc/rsa/pkcs/2048",
    "src/noir/bin/sig-check/dsc/rsa/pkcs/3072",
    "src/noir/bin/sig-check/dsc/rsa/pkcs/4096",
    "src/noir/bin/sig-check/dsc/rsa/pss/1024",
    "src/noir/bin/sig-check/dsc/rsa/pss/2048",
    "src/noir/bin/sig-check/dsc/rsa/pss/3072",
    "src/noir/bin/sig-check/dsc/rsa/pss/4096",
    "src/noir/bin/sig-check/dsc/ecdsa/nist/p256",
    "src/noir/bin/sig-check/dsc/ecdsa/nist/p384",
    "src/noir/bin/sig-check/dsc/ecdsa/nist/p521",
    "src/noir/bin/sig-check/dsc/ecdsa/brainpool/256r1",
    "src/noir/bin/sig-check/dsc/ecdsa/brainpool/256t1",
    "src/noir/bin/sig-check/dsc/ecdsa/brainpool/384r1",
    "src/noir/bin/sig-check/dsc/ecdsa/brainpool/384t1",
    "src/noir/bin/sig-check/dsc/ecdsa/brainpool/512r1",
    "src/noir/bin/sig-check/dsc/ecdsa/brainpool/512t1",
    "src/noir/bin/sig-check/id-data/ecdsa/nist/p256",
    "src/noir/bin/sig-check/id-data/ecdsa/nist/p384",
    "src/noir/bin/sig-check/id-data/ecdsa/nist/p521",
    "src/noir/bin/sig-check/id-data/ecdsa/brainpool/256r1",
    "src/noir/bin/sig-check/id-data/ecdsa/brainpool/256t1",
    "src/noir/bin/sig-check/id-data/ecdsa/brainpool/384r1",
    "src/noir/bin/sig-check/id-data/ecdsa/brainpool/384t1",
    "src/noir/bin/sig-check/id-data/ecdsa/brainpool/512r1",
    "src/noir/bin/sig-check/id-data/ecdsa/brainpool/512t1",
    "src/noir/bin/sig-check/id-data/rsa/pkcs/1024",
    "src/noir/bin/sig-check/id-data/rsa/pkcs/2048",
    "src/noir/bin/sig-check/id-data/rsa/pkcs/3072",
    "src/noir/bin/sig-check/id-data/rsa/pkcs/4096",
    "src/noir/bin/sig-check/id-data/rsa/pss/1024",
    "src/noir/bin/sig-check/id-data/rsa/pss/2048",
    "src/noir/bin/sig-check/id-data/rsa/pss/3072",
    "src/noir/bin/sig-check/id-data/rsa/pss/4096",
    "src/noir/bin/compare/citizenship",
    "src/noir/bin/compare/age",
    "src/noir/bin/exclusion-check/country",
    "src/noir/bin/disclose/flags",
    "src/noir/bin/disclose/bytes",
    "src/noir/bin/main/outer"
]
