[package]
name = "sig_check_dsc_tbs_1200_ecdsa_brainpool_384r1"
type = "bin"
authors = ["Theo Madzou", "Michael Elliot"]
compiler_version = ">=0.36.0"

[dependencies]
sig_check_ecdsa = { path = "../../../../../../../lib/sig-check/ecdsa" }
utils = { path = "../../../../../../../lib/utils" }
commitment = { path = "../../../../../../../lib/commitment/csc-to-dsc" }
