[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Enable the optimizer
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./"}]


# Ethereum Sepolia configuration
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
