[package]
name = "disclose_flags"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.32.0"

[dependencies]
disclose = { path = "../../../lib/disclose" }
commitment = { path = "../../../lib/commitment/scoped-nullifier" }
utils = { path = "../../../lib/utils" }
